module.exports = products = [
  {
    title: "Peine",
    description: "Peine para pelajes largos",
    price: 800,
    image: "/uploads/cepillo.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Champu",
    description: "Champu de uso frecuente",
    price: 600,
    image: "/uploads/champu.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Collar con cascabel",
    description: "Ideal para saber donde se encuentra tu mascota",
    price: 700,
    image: "/uploads/collar_cascabel.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Collares de cuero",
    description: "Duraderos collares de cuero para tu mascota",
    price: 1500,
    image: "/uploads/collares_cuero.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Comederos dobles de plastico",
    description: "Para el agua y la comida de tu mascota",
    price: 1100,
    image: "/uploads/comedero.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Corta Uñas",
    description: "Para mantener las uñas cortas",
    price: 2000,
    image: "/uploads/corta_uñas.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Varita masticable",
    description: "Palito de carnaza para masticar.",
    price: 300.99,
    image: "/uploads/masticable.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Sobrecitos de Pedigree",
    description: "Sobrecitos de distintos sabores para perros de raza pequeña.",
    price: 600.99,
    image: "/uploads/sobrecitos_pedigree.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Pipeta Multidosis",
    description:
      "Pipeta multidosis para todos los tamaños, pulgicida y garrapaticida.",
    price: 2000.99,
    image: "/uploads/pipeta_multidosis.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Colonia Pulgicida",
    description:
      "Vienen de distintos olores y son ideales para que tu mascota siempre huela bien y este protegida de las pulgas.",
    price: 1000,
    image: "/uploads/colonia_pulgicida.jpg",
    category: "farmacia",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Cepillo de dientes",
    description:
      "Cepillo de dientes para una buena salud en los dientes de tu mascota",
    price: 500.99,
    image: "/uploads/cepillo_dientes.jpg",
    category: "farmacia",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Pedigree Adulto 7,5kg",
    description:
      "Balanceado para perros adultos sabor carne,pollos y cereales de 7,5kg",
    price: 2500,
    image: "/uploads/pedigree_adulto_7,5.jpg",
    category: "balanceado",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Excellent Senior Perros",
    description:
      "Balanceado para perros adultos de 7 años o más sabor pollo y arroz de 7,5kg",
    price: 3100,
    image: "/uploads/excellent_adultos_5kg.jpg",
    category: "balanceado",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Excellent Senior Gatos",
    description: "Balanceado para gatos adultos sabor pollo y arroz de 7,5kg",
    price: 2800,
    image: "/uploads/excellent_adultos_cat_7,5kg.jpg",
    category: "balanceado",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Rascador para gatos",
    description: "Excelente rascador para gatos con 2 plantas",
    price: 4000,
    image: "/uploads/rascador_2pisos_gato.png",
    category: "balanceado",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Collar antiparasitario para gatos",
    description: "Tea 327 es un collar antiparasitario externo para pulgas",
    price: 1300.99,
    image: "/uploads/collar_antiparasitario_ext_gatos.jpg",
    category: "farmacia",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Gel dentrifico",
    description:
      "Max Pets es un gel dentrifico antiseptico y antiplaca para caninos y felinos",
    price: 800.99,
    image: "/uploads/gel_dentrifico_general.jpg",
    category: "farmacia",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Collar antipulgas",
    description: "Collar antipulgas para perros y gatos",
    price: 1200,
    image: "/uploads/collar-antipulgas.jpg",
    category: "farmacia",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Juguete mordedor",
    description: "Juguete mordedor para perros",
    price: 500,
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Shampoo para perros",
    description: "Shampoo para perros de pelo largo",
    price: 900,
    category: "farmacia",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Cepillo para gatos",
    description: "Cepillo para pelaje de gato",
    price: 600,
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Juguete para gatos",
    description: "Juguete para gatos con plumas",
    price: 400,
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Snack para perros",
    description: "Snack de carne para perros",
    price: 200,
    category: "balanceado",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Peine para pelo corto",
    description: "Peine para pelaje corto de perro",
    price: 800,
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Shampoo para gatos",
    description: "Shampoo para gatos de pelo corto",
    price: 700,
    category: "farmacia",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Juguete interactivo para perros",
    description: "Juguete interactivo para perros con premios",
    price: 1000,
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Comida para gatos adultos",
    description: "Comida balanceada para gatos adultos",
    price: 1200,
    image: "https://www.mrpanet.org/global_graphics/default-store-350x350.jpg",
    category: "balanceado",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Cepillo para pelo largo",
    description: "Cepillo para pelaje largo de perro o gato",
    price: 950,
    image: "https://www.mrpanet.org/global_graphics/default-store-350x350.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Shampoo para perros con piel sensible",
    description: "Shampoo para perros con piel delicada",
    price: 1100,
    image: "https://www.mrpanet.org/global_graphics/default-store-350x350.jpg",
    category: "farmacia",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Juguete de peluche para gatos",
    description: "Juguete de peluche suave para gatos",
    price: 300,
    image: "https://www.mrpanet.org/global_graphics/default-store-350x350.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Comida para cachorros de perro",
    description: "Comida balanceada para cachorros de perro",
    price: 1800,
    image: "https://www.mrpanet.org/global_graphics/default-store-350x350.jpg",
    category: "balanceado",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Juguete para perros",
    description: "Juguete resistente para perros",
    price: 500,
    image: "https://www.mrpanet.org/global_graphics/default-store-350x350.jpg",
    category: "accesorios",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Comida para gatos con problemas de sobrepeso",
    description: "Comida balanceada para gatos con sobrepeso",
    price: 1500,
    image: "https://www.mrpanet.org/global_graphics/default-store-350x350.jpg",
    category: "balanceado",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Shampoo para perros con pulgas y garrapatas",
    description: "Shampoo para perros con pulgas y garrapatas",
    price: 1300,
    image: "https://www.mrpanet.org/global_graphics/default-store-350x350.jpg",
    category: "farmacia",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
  {
    title: "Comida para perros adultos",
    description: "Comida balanceada para perros adultos",
    price: 1400,
    image: "https://www.mrpanet.org/global_graphics/default-store-350x350.jpg",
    category: "balanceado",
    stock: Number.parseInt((Math.random() * 10 + 1).toFixed(0)),
  },
];
